//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P360Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeToGroups = new HashSet<EmployeeToGroup>();
            this.ValidationTasks = new HashSet<ValidationTask>();
            this.ValidationTasks1 = new HashSet<ValidationTask>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int PrimaryRoleID { get; set; }
        public string ExternalID { get; set; }
        public int StatusID { get; set; }
    
        public virtual EmployeeStatus EmployeeStatus { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<EmployeeToGroup> EmployeeToGroups { get; set; }
        public virtual ICollection<ValidationTask> ValidationTasks { get; set; }
        public virtual ICollection<ValidationTask> ValidationTasks1 { get; set; }
    }
}
