//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P360Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeToGroup
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int GroupID { get; set; }
    
        public virtual EmployeeGroup EmployeeGroup { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
