//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P360Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidationTask
    {
        public ValidationTask()
        {
            this.ValidationResults = new HashSet<ValidationResult>();
        }
    
        public int ID { get; set; }
        public int ValidationID { get; set; }
        public int ValidatingEmployeeID { get; set; }
        public int ValidatedEmployeeID { get; set; }
        public int StatusID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual ICollection<ValidationResult> ValidationResults { get; set; }
        public virtual Validation Validation { get; set; }
        public virtual ValidationTaskStatus ValidationTaskStatus { get; set; }
    }
}
