//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P360Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidationResult
    {
        public int ID { get; set; }
        public int ValidationTaskID { get; set; }
        public int QuestionID { get; set; }
        public int Estimation { get; set; }
        public System.DateTime EstimationDate { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual ValidationTask ValidationTask { get; set; }
    }
}
