//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P360Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Validation
    {
        public Validation()
        {
            this.ValidationTasks = new HashSet<ValidationTask>();
        }
    
        public int ID { get; set; }
        public System.DateTime ValidationDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int StatusID { get; set; }
    
        public virtual ValidationStatus ValidationStatus { get; set; }
        public virtual ICollection<ValidationTask> ValidationTasks { get; set; }
    }
}
